import Head from "next/head";
import FullCalendar from "../components/fullCalendar";
import Habitcontainer from "../components/habitcontainer";
import Navbar from "../components/navbar";

export async function getServerSideProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/habits`);
  const data = await res.json();

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Navbar></Navbar>
        <div className="h-[calc(100%-3rem)] w-screen flex items-center">
          <Habitcontainer habits={data} />
          <FullCalendar habits={data} />
        </div>
      </div>
    </div>
  );
}
