import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Navbar from "../components/navbar";

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:3000/api/habits");
  const data = await res.json();
  console.log(data);
  return {
    props: { data }, // will be passed to the page component as props
  };
}

export default function Home({ data }) {
  const [newHabitName, setNewHabitName] = useState("");
  const [newHabitCategory, setNewHabitCategory] = useState("");

  const createHabit = async () => {
    const habit = {
      name: newHabitName,
      category: newHabitCategory,
    };
    const res = await fetch("http://localhost:3000/api/habits", {
      method: "POST",
      body: JSON.stringify(habit),
      headers: {
        "Content-type": "application/json; charset=utf-8",
      },
    });

    console.log(res.json());
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      {data.map((habit) => (
        <div key={habit.id} className="bg-blue-50">
          <h1>{habit.name}</h1>
          <h2>{habit.category}</h2>
        </div>
      ))}
      <div>
        <input
          type="text"
          name="name"
          value={newHabitName}
          onChange={(event) => setNewHabitName(event.target.value)}
        />
        <input
          type="text"
          name="category"
          value={newHabitCategory}
          onChange={(event) => setNewHabitCategory(event.target.value)}
        />
        <button onClick={createHabit}>submit</button>
      </div>
      <div className="bg-blue-700">Hello</div>
    </div>
  );
}
