import Head from "next/head";
import { useState } from "react";
import FullCalendar from "../components/fullCalendar";
import Habitcontainer from "../components/habitcontainer";
import Navbar from "../components/navbar";

export async function getServerSideProps(context) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/habits`);
  const data = await res.json();
  const array = [{ name: "Test", icon: "path to image" }];
  return {
    props: { data }, // will be passed to the page component as props
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Navbar></Navbar>
        <div className="h-[calc(100%-3rem)] w-screen flex items-center">
          <Habitcontainer habits={data}></Habitcontainer>
          <FullCalendar habits={data}></FullCalendar>
        </div>
      </div>
    </div>
  );
}
